---
# Installation tasks for Ubuntu
# https://dev.mysql.com/downloads/repo/apt/

- name: Try to specify preference for mysql
  shell: echo mysql-apt-config mysql-apt-config/select-server select mysql-8.0 | debconf-set-selections

- name: Add missing Apt signing key by ID from a keyserver
  ansible.builtin.apt_key:
   keyserver: keyserver.ubuntu.com
   id: "B7B3B788A8D3785C"

- name: "Install Oracle repo package"
  package:
    deb: "https://repo.mysql.com/mysql-apt-config_0.8.29-1_all.deb"

- name: "Update apt cache"
  apt:
    update_cache: yes

- name: "Install MySQL server, MySQL Router and MySQL shell packages and dependencies"
  apt:
    name:
      - mysql-server
      - mysql-shell
      - mysql-router
    state: "present"

- name: "Install python-is-python3 (Ubuntu >= Focal/20.04)"
  apt:
    name: "python-is-python3"
  when:
    - ansible_distribution_version is version_compare('20.04', '>=')

- debug:
    msg: "ansible_python_interpreter major version: {{ ansible_python.version.major }}"

- name: "Install package dependencies for ansible MySQL modules (python 2)"
  apt:
    name: "python-mysqldb"
  when:
    - ansible_python.version.major == 2     # version is a number, do not quote

- name: "Install package dependencies for ansible MySQL modules (python 3)"
  apt:
    name: 
      - "python3-pymysql"
      - "python3-mysqldb"
  when:
    - ansible_python.version.major == 3     # version is a number, do not quote

- name: "Install mc, and nano"
  apt:
    name:
      - nano
      - mc
    update_cache: yes

- name: "Adjust permissions of datadir"
  file:
    path: "{{ mysql_datadir }}"
    owner: "mysql"
    group: "mysql"
    mode: 0700
    state: "directory"